name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: yarn

      - name: Set Yarn version to 4.x
        run: |
          yarn set version 4.x
          yarn --version

      - name: Checkout Raptor repo
        uses: actions/checkout@v3
        with:
          repository: 'raptor-ml/raptor'
          fetch-depth: 1
          path: './raptor'
          ref: 'master'
      - name: Autogenerate LabSDK reference
        run: |
          pipx run pydoc-markdown

      - name: Install project dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn install

      - name: Convert ipynb files
        uses: docker://pandoc/latex:2
        with:
          entrypoint: ./.github/ipynb2md.sh

#       - name: Convert openapi2 to openapi3
#         run: |
#           curl -X 'POST' "https://converter.swagger.io/api/convert" \
#             -H "Accept: application/yaml" -H "Content-Type: application/yaml" \
#             --data-binary "@./raptor/api/proto/gen/go/apidocs.swagger.yaml" \
#             -o ./openapi.yaml
#         - name: Generate API reference
#           run: |
#             yarn docusaurus gen-api-docs all


      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
